import {test} from 'node:test';import assert from 'node:assert/strict';
import {emptyState,allocation,projectMetrics,aggregate,weekStart,careMessage,careAt,type Project,type Task} from '../shared/model.ts';
import {prepareSave} from '../server/domain.ts';
const project:Project={id:'p',name:'실제 계획',goal:'',success:'',start:'2026-09-01',end:'2026-09-10',priority:'medium',estimate:0,weekdays:[0,1,2,3,4,5,6],archived:false};
function task(id:string):Task{return {id,name:id,projectId:'p',stageId:'',date:'2026-09-01',originalDate:'2026-09-01',priority:'medium',tags:'',estimate:30,status:'todo',reason:'',note:'',unplanned:false,archived:false,createdAt:'',completedAt:'',ruleId:''}}
test('가중치 1·1·3·5: 10일 배분, 20% 완료 후 가용 5일은 촉박',()=>{const s=emptyState();s.projects=[project];s.stages=[1,1,3,5].map((weight,i)=>({id:String(i),name:String(i),projectId:'p',weight,order:i,manual:i<2?100:0,archived:false}));assert.deepEqual(allocation(s,project).map(a=>a.days),[1,1,3,5]);const m=projectMetrics(s,project,'2026-09-06');assert.equal(m.progress,.2);assert.equal(m.remaining,8);assert.equal(m.available,5);assert.equal(m.status,'촉박')});
test('미정·빈 단계·작업 요일 없음과 날짜 경계',()=>{const s=emptyState();assert.equal(projectMetrics(s,project,'2026-09-01').status,'판단 불가');assert.deepEqual(allocation(s,{...project,weekdays:[]}),[]);assert.equal(weekStart('2026-09-13'),'2026-09-07')});
test('자기관리 미기록과 과거 기준을 보존하고 숫자 대신 문구 반환',()=>{const s=emptyState();assert.match(careMessage(s,'2026-09-01','2026-09-07'),/기록이 아직/);s.care=[{id:'v1',effective:'2026-09-01',goal:'나의 이상',categories:[{id:'c',name:'운동',threshold:4,actions:[{id:'a',name:'걷기'}]}]}];const next=structuredClone(s);next.logs=[{id:'l',date:'2026-09-01',actionId:'a',categoryId:'c',name:'조작',category:'조작',threshold:1,status:'done'}];const saved=prepareSave(s,next,new Date('2026-09-02T12:00:00Z'));assert.equal(saved.logs[0].name,'걷기');assert.equal(saved.logs[0].threshold,4);saved.care.push({...s.care[0],id:'v2',effective:'2026-09-03',goal:'새 목표'});assert.equal(careAt(saved,'2026-09-02')?.goal,'나의 이상');assert.doesNotMatch(careMessage(saved,'2026-09-01','2026-09-07'),/\d|%/)});
test('완료를 두 번 요청해도 완료일과 완료 집계는 한 번만 변함',()=>{const s=emptyState();s.projects=[project];s.tasks=[task('t')];const a=structuredClone(s);a.tasks[0].status='done';const first=prepareSave(s,a,new Date('2026-09-02T12:00:00Z'));const second=prepareSave(first,first,new Date('2026-09-03T12:00:00Z'));assert.equal(second.tasks[0].completedAt,'2026-09-02T12:00:00.000Z');assert.equal(aggregate(second,second.tasks,'2026-09-04').done.length,1);assert.equal(aggregate(second,second.tasks,'2026-09-04').late.length,0)});
test('이월은 최초 예정일을 보존하고 완료 취소는 완료 시간을 초기화',()=>{const s=emptyState();s.projects=[project];s.tasks=[{...task('t'),status:'done',completedAt:'2026-09-02T00:00:00Z'}];const n=structuredClone(s);n.tasks[0].date='2026-09-10';n.tasks[0].originalDate='2026-09-10';n.tasks[0].status='doing';const result=prepareSave(s,n);assert.equal(result.tasks[0].originalDate,'2026-09-01');assert.equal(result.tasks[0].completedAt,'')});
test('예상·실제 차이와 막힘은 업무별 집계, 삭제와 취소 제외',()=>{const s=emptyState();s.tasks=[task('a'),{...task('b'),archived:true},{...task('c'),status:'cancelled'}];s.executions=[{id:'e1',taskId:'a',start:'',end:'',minutes:45,reason:'이슈',date:'2026-09-01',createdAt:''},{id:'e2',taskId:'a',start:'',end:'',minutes:5,reason:'이슈',date:'2026-09-01',createdAt:''}];const a=aggregate(s,s.tasks,'2026-09-02');assert.equal(a.planned.length,1);assert.equal(a.blocked.length,1);assert.equal(a.actual,50);assert.equal(a.difference,20);assert.equal(aggregate(emptyState(),[]).actual,0)});
test('실행 시간은 시작·종료로 계산하며 계획을 변경하지 않음',()=>{const s=emptyState();s.projects=[project];s.tasks=[task('t')];const n=structuredClone(s);n.executions.push({id:'e',taskId:'t',start:'2026-09-01T00:00:00Z',end:'2026-09-01T00:45:00Z',minutes:99,reason:'',date:'2026-09-01',createdAt:''});const result=prepareSave(s,n);assert.equal(result.executions[0].minutes,45);assert.deepEqual(result.projects,s.projects);assert.equal(result.tasks[0].estimate,30)});
test('중복 반복일과 잘못된 관계·가중치 차단',()=>{const s=emptyState();s.projects=[project];const n=structuredClone(s);n.tasks=[{...task('a'),ruleId:'r'},{...task('b'),ruleId:'r'}];assert.throws(()=>prepareSave(s,n),/중복/);n.tasks=[{...task('a'),stageId:'missing'}];assert.throws(()=>prepareSave(s,n),/단계/);n.tasks=[];n.stages=[{id:'st',projectId:'p',name:'단계',weight:0,order:0,manual:null,archived:false}];assert.throws(()=>prepareSave(s,n))});
test('소수 작업일 배분은 마감일을 넘지 않음',()=>{const s=emptyState();s.stages=Array.from({length:13},(_,i)=>({id:String(i),name:'과제',projectId:'p',weight:1,order:i,manual:null,archived:false}));const a=allocation(s,{...project,end:'2026-09-02'});assert.equal(a.length,13);assert.ok(a.every(x=>x.end<='2026-09-02'));assert.ok(Math.abs(a.reduce((n,x)=>n+x.days,0)-2)<1e-10)});
