import { z } from 'zod';
const id=z.string().min(1).max(100);
const text=z.string().max(4000);
export const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'올바른 날짜를 입력하세요');
const optionalDate=z.union([date,z.literal('')]);
const number=z.number().finite().min(0).max(1e7);
export const categorySchema=z.object({id,name:z.string().min(1).max(100),threshold:z.number().int().min(1).max(8),actions:z.array(z.object({id,name:z.string().min(1).max(150)})).max(8)});
export const careVersionSchema=z.object({id,effective:date,goal:text,categories:z.array(categorySchema).max(8)});
export const projectColorSchema=z.enum(['apricot','sky','lavender','rose','lemon','mint','blue','coral']);
export const projectSchema=z.object({id,name:z.string().min(1).max(150),goal:text,success:text,start:optionalDate,end:optionalDate,priority:z.enum(['high','medium','low']),color:projectColorSchema.default('sky'),estimate:number,weekdays:z.array(z.number().int().min(0).max(6)).max(7),archived:z.boolean()}).refine(p=>!p.start||!p.end||p.end>=p.start,'마감일은 시작일 이후여야 합니다');
export const stageSchema=z.object({id,projectId:id,name:z.string().min(1).max(150),weight:z.number().int().min(1).max(10).nullable(),order:z.number().int().min(0),manual:z.number().min(0).max(100).nullable(),archived:z.boolean()});
export const taskSchema=z.object({id,projectId:z.string().max(100),stageId:z.string().max(100),name:z.string().min(1).max(200),date:optionalDate,originalDate:optionalDate,priority:z.enum(['high','medium','low']),tags:text,estimate:number,status:z.enum(['todo','doing','done','blocked','cancelled']),reason:text,note:text,unplanned:z.boolean(),archived:z.boolean(),completedAt:z.string(),createdAt:z.string(),ruleId:z.string().max(100)});
export const executionSchema=z.object({id,taskId:id,start:z.string(),end:z.string(),minutes:number,reason:text,date,createdAt:z.string()}).refine(e=>(!e.start||!Number.isNaN(Date.parse(e.start)))&&(!e.end||!Number.isNaN(Date.parse(e.end)))&&(!e.start||!e.end||Date.parse(e.end)>=Date.parse(e.start)),'시작/종료 시각을 확인하세요');
export const ruleSchema=z.object({id,projectId:z.string(),stageId:z.string(),name:z.string().min(1).max(150),target:z.number().int().min(1).max(7),weekdays:z.array(z.number().int().min(0).max(6)).max(7),start:date,archived:z.boolean()});
export const planSchema=z.object({id,projectId:id,createdAt:z.string(),allocations:z.array(z.object({stageId:id,start:date,end:date,days:number,baseProgress:z.number().min(0).max(1)}))});
export const stateSchema=z.object({timezone:z.string().refine(s=>{try{new Intl.DateTimeFormat('en',{timeZone:s});return true}catch{return false}},'시간대를 확인하세요'),care:z.array(careVersionSchema),logs:z.array(z.object({id,date,actionId:id,categoryId:id,status:z.enum(['done','missed']),name:text,category:text,threshold:z.number().int().min(1).max(8)})),projects:z.array(projectSchema),stages:z.array(stageSchema),tasks:z.array(taskSchema),executions:z.array(executionSchema),rules:z.array(ruleSchema),plans:z.array(planSchema),reviews:z.array(z.object({id,date,area:z.enum(['care','projects']),text,closed:z.boolean()}))});
export type State=z.infer<typeof stateSchema>;
export type Project=z.infer<typeof projectSchema>; export type Stage=z.infer<typeof stageSchema>; export type Task=z.infer<typeof taskSchema>; export type Execution=z.infer<typeof executionSchema>; export type CareVersion=z.infer<typeof careVersionSchema>;
export type Snapshot={state:State;revision:number};
export type History={revision:number;created_at:string;label:string;data:State};
export function emptyState():State{return {timezone:'Asia/Seoul',care:[],logs:[],projects:[],stages:[],tasks:[],executions:[],rules:[],plans:[],reviews:[]}}
export function uid(){return crypto.randomUUID()}
export function today(zone='Asia/Seoul',now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
export function addDays(d:string,n:number){const x=new Date(`${d}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}
export function weekStart(d:string){return addDays(d,-((new Date(d+'T12:00:00Z').getUTCDay()+6)%7))}
export function daysBetween(start:string,end:string,weekdays:number[]=[0,1,2,3,4,5,6]){if(!start||!end||end<start)return [];const out:string[]=[];for(let d=start;d<=end&&out.length<10000;d=addDays(d,1)){if(weekdays.includes(new Date(d+'T12:00:00Z').getUTCDay()))out.push(d);if(Date.parse(d)-Date.parse(start)>3660*86400000)break}return out}
export function careAt(s:State,d:string){return [...s.care].filter(v=>v.effective<=d).sort((a,b)=>a.effective.localeCompare(b.effective)).at(-1)}
export function stageProgress(s:State,stage:Stage){if(stage.manual!==null)return stage.manual/100;const ts=s.tasks.filter(t=>t.stageId===stage.id&&!t.archived&&t.status!=='cancelled'&&!t.ruleId);return ts.length?ts.filter(t=>t.status==='done').length/ts.length:0}
export function allocation(s:State,p:Project,from=p.start,replan=false){const stages=s.stages.filter(x=>x.projectId===p.id&&!x.archived).sort((a,b)=>a.order-b.order);const days=daysBetween(from,p.end,p.weekdays);if(!days.length||!stages.length||stages.some(x=>x.weight===null))return [];const weights=stages.map(x=>x.weight!*(replan?1-stageProgress(s,x):1));const sum=weights.reduce((a,b)=>a+b,0);if(!sum)return [];let cursor=0;return stages.flatMap((stage,i)=>{if(!weights[i])return [];const amount=days.length*weights[i]/sum;const start=days[Math.min(Math.floor(cursor+1e-9),days.length-1)];cursor+=amount;return [{stageId:stage.id,start,end:days[Math.min(Math.max(0,Math.ceil(cursor-1e-9)-1),days.length-1)],days:amount,baseProgress:replan?stageProgress(s,stage):0}]})}
export function projectMetrics(s:State,p:Project,d:string,onlyStage?:string){const stages=s.stages.filter(x=>x.projectId===p.id&&!x.archived&&(!onlyStage||x.id===onlyStage));const sum=stages.reduce((a,b)=>a+(b.weight??0),0);const progress=sum?stages.reduce((a,b)=>a+(b.weight??0)*stageProgress(s,b),0)/sum:0;const plans=s.plans.filter(x=>x.projectId===p.id);const alloc=(plans.at(-1)?.allocations??allocation(s,p)).filter(a=>!onlyStage||a.stageId===onlyStage);if(!stages.length||stages.some(x=>x.weight===null)||!alloc.length)return {progress,status:'판단 불가',remaining:0,available:0};const remaining=alloc.reduce((a,b)=>{const st=stages.find(x=>x.id===b.stageId);return a+(st?b.days*Math.max(0,1-stageProgress(s,st))/Math.max(0.00001,1-b.baseProgress):0)},0);const closed=s.reviews.some(r=>r.area==='projects'&&r.date===d&&r.closed);const end=onlyStage?alloc[0].end:p.end;const available=daysBetween(closed?addDays(d,1):d,end,p.weekdays).length;let status=progress>=1?'완료':end<d?'기한 초과':remaining===0?'판단 불가':(available-remaining)/remaining>=.2?'여유':available>=remaining?'주의':'촉박';if(status==='여유'&&alloc.some(a=>a.end<d&&stageProgress(s,stages.find(x=>x.id===a.stageId)!)<1))status='주의';return {progress,status,remaining,available}}
export function careMessage(s:State,start:string,end:string){const logs=s.logs.filter(l=>l.date>=start&&l.date<=end);if(!logs.length)return '기록이 아직 없어요. 작은 실천부터 남겨볼까요?';const groups=new Map<string,{done:number;threshold:number}>();for(const l of logs){const key=l.date+l.categoryId;const g=groups.get(key)??{done:0,threshold:l.threshold};g.done+=Number(l.status==='done');groups.set(key,g)}const score=[...groups.values()].reduce((a,g)=>a+Math.min(g.done/g.threshold,1),0)/groups.size;return score>=.75?'나를 돌보는 실천을 잘 이어가고 있어요. 오늘의 나에게 다정한 칭찬을 건네요.':'작게 실천한 것도 소중해요. 내일도 무리하지 않고 편하게 이어가요.'}
export function aggregate(s:State,tasks:Task[],d=today('Asia/Seoul')){const active=tasks.filter(t=>!t.archived&&t.status!=='cancelled');const ids=new Set(active.map(t=>t.id));const executions=s.executions.filter(e=>ids.has(e.taskId));const groups={planned:active,done:active.filter(t=>t.status==='done'),late:active.filter(t=>t.status!=='done'&&t.date!==''&&t.date<d),blocked:active.filter(t=>Boolean(t.reason.trim())||executions.some(e=>e.taskId===t.id&&e.reason.trim()))};const estimate=active.reduce((a,t)=>a+t.estimate,0),actual=executions.reduce((a,e)=>a+e.minutes,0);return {...groups,estimate,actual,difference:actual-estimate}}
